language: node_js
node_js:
- 9
cache:
  pip: true
  directories:
  - node_modules
script: npm run build
before_deploy:
- pip install --user awscli
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: mooc.fi
  local-dir: "build"
  skip_cleanup: true
  region: eu-central-1
  on:
    branch: master
env:
  global:
  - secure: OxSo2NctJWefH/MAN7t97DRhBIiL5r+IQDxljLk8fKXiw5+8G4gJwot9ymf81xDqej0Itrc+mtQjql/o8M92A1BP/c+Crr296KWwLTpJa1zLOTH65PdwNE7cX0kAf99yzoWoBdW4EdBQNR4TQwBSrIMoGubZKUMPo3cCp0eFwZpO2ctDGzdACjEwUye8vvXsX7vuvWJXgsu+3REgIhU30DDNpH7nV3p4WA/Bs3PJHNzcXKgU4ScR/6dcdCuQ3DJOLg+WUlvC5Y0dyt/76tPJvv2yoAu3egoskxRk4E4NuNlIYdjQYmAjWARMsviZnpPzZZmEpFmM1CVXaZhqlsQX+3M3CJVdQpGttdYW3DqOudkCkIzAMQKam/CY9VqqexV50N5KzB94d91O8NOceexbrUDlAM50khAOBq9s+VVFew3yBqEGtWMNBs8RXf9Rse2O4OFySfAYHvGbjw5q9KOI+kEI0Q5CV8qz8pisWQhlCsSqx//i7Lwya/YutOe+sbhLjXIoTL+P+ZX7d7J+QmvBhgkaihjZqgSkNh6YMc6St7F+xi+se97YU/SjfXO2Ou9RPDWRehJS/9Np8HTVWtAsyA5+PdxDpr2kBn2eZe3ggWemWaR6DyJqyLzFCXcu+nBz5/GQqxYJjyhIzcCnHebiu4EAjY+BBghbyFGi+/tVEkE=
  - secure: dRy+7L+1X64T2OswJrsEcolpAA+9xN8a9J/lCMqnR+Y9hWQyqB9NNIHSjvYEII29UlvvPJy37+3fSzHrM+JM8fygDlbUTStBCA4Xyn9l+6skmqVNBqOGITs+e+pJgVFoUiCjnTdAB7ZdnSt8HaMcopGHdJ2NtN4fCPmfjs7yDJWeddSUkDLCkj1jfHATH+PGTMXG0C/o810GT4mFHlz/enFir3noUafqQdGEzAjnJT4ne8SR7SX/6/DKZBB+BBOnjZIGcvuwkQmmEVulSjkEKgmecUDyf/QXsWHH8CPnuyRKXr+4qnIX/iG18U63JLtuxcnnL8K2afCcud0ZWwqYYFmCm9Yo/qmEIvR6GPTQqslBhU2NA6G2VaDoBt6CQ4Zspu20Qg6LVf1pr6WoIQ+C/l+Ga8L4f8XjczEqX1uuM0NCsG63mYtd9D5q1BAr9dV/l9KHD/1D4TY3UwrufAVPfdOgh07yvMjcwbrc8cc562jhfneTqe+cPvIF5C2KYeodefyUJefpHiQ/8UhmtVDC7WR/Xoq9H50xVjUvDde4QEAbfyQI+rhgGvn6HxSgJfGQglZJ/1pEW5KND09Mq2LQkMYfVMCAqYr0+d+scvGkad8r+g1mC6OhCA2nf9yIWf6Avttmkqsej6b6Xgu2DccFrdl9s6K9GcW/Alb1c+roFoQ=
